// <auto-generated />
namespace PersonalTask.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TaskEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201603052152084_TaskEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
